---
- name: Common baseline
  hosts: all
  become: true
  tasks:
    - name: Ensure basic packages are present
      ansible.builtin.apt:
        name:
          - qemu-guest-agent
          - curl
          - vim
          - git
        state: present
        update_cache: true

- name: Configure k3s server
  ansible.builtin.import_playbook: k3s-server.yaml

- name: Configure k3s agents
  ansible.builtin.import_playbook: k3s-agent.yaml
