---
- name: Configure jumpbox
  ansible.builtin.import_playbook: jumpbox.yaml

- name: Configure k3s server
  ansible.builtin.import_playbook: k3s-server.yaml

- name: Configure k3s agents
  ansible.builtin.import_playbook: k3s-agent.yaml
